services:
  db:
    deploy:
      replicas: 1
    image: postgres:17
    shm_size: 1g
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    ports:
      - 3000:3000

volumes:
  db_data:
