version: "0.5"

processes:
  postgresql:
    command: postgres
    readiness_probe:
      exec:
        command: pg_isready -h localhost -p 5432 -U postgres -d local
    availability:
      restart: on_failure
  init_db:
    namespace: init
    command: |
      sh config/init-db.sh
    availability:
      restart: on_failure
  drizzle-studio:
    command: bun run db:studio
  web:
    command: bun run dev
    availability:
      restart: on_failure
  # inngest:
  #   command: bun run inngest:dev
  #   availability:
  #     restart: on_failure
